[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
BinaryTrees = "b5b2f71e-4d2a-452d-9d2b-18613792c179"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
EasyFit = "fde71243-0cda-4261-b7c7-4845bd106b21"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TreeProcesses = "fe9c5e76-98a0-40b3-a46c-727041eeba4e"

[compat]
BinaryTrees = "0.2"
TreeProcesses = "0.1"